name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Run Tests
      run: dotnet test --verbosity normal
      
    - name: Fetch Release Info
      # You may pin to the exact commit or the version.
      # uses: abatilo/release-info-action@cbceb53f7939d60b0933ae3ac125c1a94ddf0149
      uses: abatilo/release-info-action@v1.1.0
      id: release
      with:
        # The user or org for this repo
        owner: TobyMeehan
        # The name of the repo itself
        repo: TypeQuery
    - name: Publish to NuGet
      # You may pin to the exact commit or the version.
      # uses: brandedoutcast/publish-nuget@c12b8546b67672ee38ac87bea491ac94a587f7cc
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: TypeQuery/TypeQuery.csproj
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: TypeQuery
        # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        # VERSION_FILE_PATH: # optional
        # Regex pattern to extract version info in a capturing group
        # VERSION_REGEX: # optional, default is ^\s*<Version>(.*)<\/Version>\s*$
        # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
        VERSION_STATIC: ${{ steps.release.outputs.latest_tag }}
        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: false # optional, default is true
        # Format of the git tag, [*] gets replaced with actual version
        # TAG_FORMAT: # optional, default is v*
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.NUGET_DEPLOY_KEY }} # optional
        # NuGet server uri hosting the packages, defaults to https://api.nuget.org
        # NUGET_SOURCE: # optional, default is https://api.nuget.org
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        # INCLUDE_SYMBOLS: # optional
    
      
